name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # O usa "master" si tu repo lo usa

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Iniciar sesión en GitHub Container Registry
        run: echo "${{ secrets.PERSONAL_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Convertir owner a minúsculas
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Construir la imagen Docker
        run: |
          docker build -t ghcr.io/${{ env.OWNER_LC }}/amiharder-booking:latest .
      
      - name: Subir la imagen a GHCR
        run: |
          docker push ghcr.io/${{ env.OWNER_LC }}/amiharder-booking:latest
