name: Ejecutar Batch Diario en Node.js

on:
  schedule:
    - cron: "0 6 * * 0-3"  # Invierno
    - cron: "0 5 * * 0-3"  # Verano
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

jobs:
  run-batch:
    runs-on: ubuntu-latest

    steps:
      - name: Iniciar sesión en GHCR
        run: echo "${{ secrets.PERSONAL_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Ejecutar el contenedor
        run: |
          docker run --rm \
            -e MAIL=${{ secrets.MAIL }} \
            -e PASS=${{ secrets.PASS }} \
            -e BOX=${{ vars.BOX }} \
            -e TIME=${{ vars.TIME }} \
            -e HOST=${{ vars.HOST }} \
            -e RUZAFA_HOST=${{ vars.RUZAFA_HOST }} \
            -e CLUB=${{ vars.CLUB }} \
            ghcr.io/${{ github.repository }}/amiharder-booking:latest
