name: Ejecutar Batch Diario en Node.js

on:
  schedule:
    - cron: "0 6 * * 0-3"  # Invierno
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

jobs:
  run-batch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar el script
        env:
          MAIL: ${{ vars.MAIL }}
          PASS: ${{ secrets.PASS }}  # Secreto
          BOX: ${{ vars.BOX }}
          TIME: ${{ vars.TIME }}
          HOST: ${{ vars.HOST }}
          RUZAFA_HOST: ${{ vars.RUZAFA_HOST }}
          CLUB: ${{ vars.CLUB }}
          EXEC_HOUR: ${{ vars.EXEC_HOUR }}
          EXEC_MIN: ${{ vars.EXEC_MIN }}
        run: node index.js
